<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>用户注册通知</title>
</head>
<body>
    <p>user.name您好，恭喜您，已经成为本站会员！</p>
    <table>
        <tr>
            <td>用户名：</td>
            <td>user.name您好，恭喜您，已经成为本站会员！</p></td>
            <tr>
                <td>用户名：</td><td>${user}</td>
             </tr>
            <tr>
                <td>密码：</td><td>${password}</td>
            </tr>
        </tr>
    </table>
</body>
</html>